# config/routes.yaml

controllers:
    resource: '../src/Controller/'
    type: annotation

app_routes:
    resource: '../src/Controller/MainController.php'
    type: annotation

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

